import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Discover - MyLittlePlant</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href="/product/citronella">Hello World</Link>
        </div>
    );
};

export default Home;
